//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class oauth_access_token
    {
        public string token_id { get; set; }
        public byte[] token { get; set; }
        public string authentication_id { get; set; }
        public string user_name { get; set; }
        public string client_id { get; set; }
        public byte[] authentication { get; set; }
        public string refresh_token { get; set; }
        public byte[] defaultOAuth2AccessToken { get; set; }
    }
}
