//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class oauth_client_details
    {
        public string client_id { get; set; }
        public string resource_ids { get; set; }
        public string client_secret { get; set; }
        public string scope { get; set; }
        public string authorized_grant_types { get; set; }
        public string web_server_redirect_uri { get; set; }
        public string authorities { get; set; }
        public Nullable<int> access_token_validity { get; set; }
        public Nullable<int> refresh_token_validity { get; set; }
        public string additional_information { get; set; }
        public string autoapprove { get; set; }
    }
}
