//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDocument
    {
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string DocName { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CreatedUser { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
