//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_admission_infomation
    {
        public long id { get; set; }
        public System.DateTime create_date { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string uuid_key { get; set; }
        public Nullable<bool> voided { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public string blockSubjectCode { get; set; }
        public Nullable<int> candidateArea { get; set; }
        public string candidateCodeType { get; set; }
        public string code { get; set; }
        public Nullable<double> coefficient1 { get; set; }
        public Nullable<double> coefficient2 { get; set; }
        public Nullable<double> coefficient3 { get; set; }
        public Nullable<double> coefficient4 { get; set; }
        public string fullName { get; set; }
        public Nullable<double> mark1 { get; set; }
        public Nullable<double> mark2 { get; set; }
        public Nullable<double> mark3 { get; set; }
        public Nullable<double> mark4 { get; set; }
        public string subjectName1 { get; set; }
        public string subjectName2 { get; set; }
        public string subjectName3 { get; set; }
        public string subjectName4 { get; set; }
    }
}
