//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_staff()
        {
            this.tbl_calendar_event_attendee = new HashSet<tbl_calendar_event_attendee>();
            this.tbl_course_subject = new HashSet<tbl_course_subject>();
            this.tbl_course_subject_timetable = new HashSet<tbl_course_subject_timetable>();
            this.tbl_course_subject_timetable1 = new HashSet<tbl_course_subject_timetable>();
            this.tbl_enrollment_class = new HashSet<tbl_enrollment_class>();
            this.tbl_position_staff = new HashSet<tbl_position_staff>();
            this.tbl_timesheet = new HashSet<tbl_timesheet>();
            this.tbl_staff_disciplinary_history = new HashSet<tbl_staff_disciplinary_history>();
            this.tbl_staff_work_schedule = new HashSet<tbl_staff_work_schedule>();
            this.tbl_staff_allowance_history = new HashSet<tbl_staff_allowance_history>();
            this.tbl_staff_salary_history = new HashSet<tbl_staff_salary_history>();
            this.tbl_staff_reward_history = new HashSet<tbl_staff_reward_history>();
            this.tbl_staff_travelling_history = new HashSet<tbl_staff_travelling_history>();
            this.tbl_staff_salary_property = new HashSet<tbl_staff_salary_property>();
            this.tbl_staff_education_history = new HashSet<tbl_staff_education_history>();
            this.tbl_staff_civil_servant_grade = new HashSet<tbl_staff_civil_servant_grade>();
            this.tbl_staff_labour_agreement = new HashSet<tbl_staff_labour_agreement>();
            this.tbl_staff_family_relationship = new HashSet<tbl_staff_family_relationship>();
        }
    
        public Nullable<int> current_working_status { get; set; }
        public string social_insurance_number { get; set; }
        public string staff_code { get; set; }
        public long id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_calendar_event_attendee> tbl_calendar_event_attendee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_course_subject> tbl_course_subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_course_subject_timetable> tbl_course_subject_timetable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_course_subject_timetable> tbl_course_subject_timetable1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_enrollment_class> tbl_enrollment_class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_position_staff> tbl_position_staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_timesheet> tbl_timesheet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_staff_disciplinary_history> tbl_staff_disciplinary_history { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_staff_work_schedule> tbl_staff_work_schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_staff_allowance_history> tbl_staff_allowance_history { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_staff_salary_history> tbl_staff_salary_history { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_staff_reward_history> tbl_staff_reward_history { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_staff_travelling_history> tbl_staff_travelling_history { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_staff_salary_property> tbl_staff_salary_property { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_staff_education_history> tbl_staff_education_history { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_staff_civil_servant_grade> tbl_staff_civil_servant_grade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_staff_labour_agreement> tbl_staff_labour_agreement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_staff_family_relationship> tbl_staff_family_relationship { get; set; }
    }
}
