//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_student_scholarship_stock_detail
    {
        public long id { get; set; }
        public System.DateTime create_date { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string uuid_key { get; set; }
        public Nullable<bool> voided { get; set; }
        public Nullable<double> semester_balance_value { get; set; }
        public Nullable<double> semester_receive_value { get; set; }
        public Nullable<double> semester_value { get; set; }
        public Nullable<double> semester_withdraw_value { get; set; }
        public Nullable<double> stock_semester_value { get; set; }
        public Nullable<double> total_balance_value { get; set; }
        public Nullable<double> total_changed_value { get; set; }
        public Nullable<double> total_receive_value { get; set; }
        public Nullable<double> total_stock_value { get; set; }
        public Nullable<double> total_tuition_fee_balance { get; set; }
        public Nullable<double> total_value { get; set; }
        public Nullable<double> total_withdraw_value { get; set; }
        public Nullable<double> tuition_fee_balance { get; set; }
        public Nullable<long> scholarship_fund_id { get; set; }
        public Nullable<long> scholarship_stock_id { get; set; }
    
        public virtual tbl_scholarship_fund tbl_scholarship_fund { get; set; }
        public virtual tbl_student_scholarship_stock tbl_student_scholarship_stock { get; set; }
    }
}
