//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_register_period_time_config
    {
        public long id { get; set; }
        public System.DateTime create_date { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string uuid_key { get; set; }
        public Nullable<bool> voided { get; set; }
        public Nullable<System.DateTime> end_register_date { get; set; }
        public Nullable<bool> is_grant { get; set; }
        public Nullable<System.DateTime> start_register_date { get; set; }
        public Nullable<long> enrollment_class_id { get; set; }
        public Nullable<long> register_period_id { get; set; }
    
        public virtual tbl_enrollment_class tbl_enrollment_class { get; set; }
        public virtual tbl_semester_register_period tbl_semester_register_period { get; set; }
    }
}
