//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_student_reward
    {
        public long id { get; set; }
        public System.DateTime create_date { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string uuid_key { get; set; }
        public Nullable<bool> voided { get; set; }
        public Nullable<System.DateTime> decision_date { get; set; }
        public Nullable<int> first_sort_student_semester_behavior_mark { get; set; }
        public Nullable<int> first_sort_student_semester_summary_mark { get; set; }
        public Nullable<double> first_student_semester_behavior_mark { get; set; }
        public Nullable<double> first_student_semester_summary_mark { get; set; }
        public Nullable<bool> is_end_course_year { get; set; }
        public Nullable<long> number_disciplined { get; set; }
        public Nullable<long> number_rewarded { get; set; }
        public string reason { get; set; }
        public Nullable<int> second_sort_student_semester_behavior_mark { get; set; }
        public Nullable<int> second_sort_student_semester_summary_mark { get; set; }
        public Nullable<double> second_student_semester_behavior_mark { get; set; }
        public Nullable<double> second_student_semester_summary_mark { get; set; }
        public Nullable<int> sort_student_behavior_summary_mark { get; set; }
        public Nullable<int> sort_student_school_year_behavior_mark { get; set; }
        public Nullable<int> second_sort_student_school_year_summary_mark { get; set; }
        public Nullable<int> sort_student_summary_mark { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<double> student_behavior_summary_mark { get; set; }
        public Nullable<double> student_school_year_behavior_mark { get; set; }
        public Nullable<double> student_school_year_summary_mark { get; set; }
        public Nullable<double> student_summary_mark { get; set; }
        public Nullable<long> reward_id { get; set; }
        public Nullable<long> reward_decree_id { get; set; }
        public Nullable<long> school_year_id { get; set; }
        public Nullable<long> semester_id { get; set; }
        public Nullable<long> student_id { get; set; }
        public Nullable<long> student_reward_condition { get; set; }
    
        public virtual tbl_reward tbl_reward { get; set; }
        public virtual tbl_reward_decree tbl_reward_decree { get; set; }
        public virtual tbl_semester tbl_semester { get; set; }
        public virtual tbl_shool_year tbl_shool_year { get; set; }
        public virtual tbl_student tbl_student { get; set; }
        public virtual tbl_student_reward_condition tbl_student_reward_condition { get; set; }
    }
}
