//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_student_tuition_fee_calculate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_student_tuition_fee_calculate()
        {
            this.tbl_inventory_item = new HashSet<tbl_inventory_item>();
            this.tbl_receive_pay_able_detail = new HashSet<tbl_receive_pay_able_detail>();
            this.tbl_student_tuition_fee_calculate_detail = new HashSet<tbl_student_tuition_fee_calculate_detail>();
        }
    
        public long id { get; set; }
        public System.DateTime create_date { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string uuid_key { get; set; }
        public Nullable<bool> voided { get; set; }
        public Nullable<double> account { get; set; }
        public Nullable<System.DateTime> calculate_date { get; set; }
        public Nullable<double> discount_percent { get; set; }
        public Nullable<double> discount_value { get; set; }
        public Nullable<double> first_time_learn_fee { get; set; }
        public Nullable<bool> is_lock { get; set; }
        public Nullable<int> number_of_credit { get; set; }
        public Nullable<int> number_of_subject { get; set; }
        public Nullable<double> relearn_fee { get; set; }
        public Nullable<double> rest_amount { get; set; }
        public Nullable<double> total_tuition_fee { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<double> upgrade_mark_fee { get; set; }
        public Nullable<long> discount_tuition_fee_id { get; set; }
        public Nullable<long> receive_payable_id { get; set; }
        public Nullable<long> register_periods_id { get; set; }
        public Nullable<long> semester_id { get; set; }
        public Nullable<long> student_id { get; set; }
    
        public virtual tbl_discount_tuition_fee tbl_discount_tuition_fee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_inventory_item> tbl_inventory_item { get; set; }
        public virtual tbl_receive_pay_able tbl_receive_pay_able { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_receive_pay_able_detail> tbl_receive_pay_able_detail { get; set; }
        public virtual tbl_semester tbl_semester { get; set; }
        public virtual tbl_semester_register_period tbl_semester_register_period { get; set; }
        public virtual tbl_student tbl_student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_tuition_fee_calculate_detail> tbl_student_tuition_fee_calculate_detail { get; set; }
    }
}
