//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_education_voucher_detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_education_voucher_detail()
        {
            this.tbl_voucher_detail_recieve_pay_able_link = new HashSet<tbl_voucher_detail_recieve_pay_able_link>();
            this.tbl_inventory_item = new HashSet<tbl_inventory_item>();
        }
    
        public long id { get; set; }
        public System.DateTime create_date { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string uuid_key { get; set; }
        public Nullable<bool> voided { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<double> discount_amount { get; set; }
        public Nullable<double> discount_percent { get; set; }
        public Nullable<int> is_receive { get; set; }
        public string note { get; set; }
        public Nullable<double> received_amount { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<long> education_voucher_id { get; set; }
        public Nullable<long> fee_item_id { get; set; }
        public Nullable<long> fee_item_detai_id { get; set; }
        public Nullable<long> receive_pay_able_id { get; set; }
        public Nullable<long> receive_pay_able_detail_id { get; set; }
        public Nullable<bool> view_able { get; set; }
        public Nullable<double> rest_amount { get; set; }
        public Nullable<double> amount_done { get; set; }
    
        public virtual tbl_education_voucher tbl_education_voucher { get; set; }
        public virtual tbl_receive_pay_able tbl_receive_pay_able { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_voucher_detail_recieve_pay_able_link> tbl_voucher_detail_recieve_pay_able_link { get; set; }
        public virtual tbl_receive_pay_able_detail tbl_receive_pay_able_detail { get; set; }
        public virtual tbl_fee_item tbl_fee_item { get; set; }
        public virtual tbl_fee_item_detail tbl_fee_item_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_inventory_item> tbl_inventory_item { get; set; }
    }
}
