//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_student_mark
    {
        public long id { get; set; }
        public System.DateTime create_date { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string uuid_key { get; set; }
        public Nullable<bool> voided { get; set; }
        public Nullable<double> coeffiecient { get; set; }
        public Nullable<int> exam_round { get; set; }
        public Nullable<bool> is_lock { get; set; }
        public Nullable<bool> is_updated { get; set; }
        public Nullable<double> mark { get; set; }
        public Nullable<int> mark_status { get; set; }
        public string note { get; set; }
        public Nullable<double> old_mark { get; set; }
        public Nullable<double> original_mark { get; set; }
        public Nullable<int> update_type { get; set; }
        public Nullable<long> mark_type_id { get; set; }
        public Nullable<long> semester_subject_id { get; set; }
        public Nullable<long> special_point { get; set; }
        public Nullable<long> student_id { get; set; }
        public Nullable<long> student_course_subject_id { get; set; }
        public Nullable<long> student_exam_room_id { get; set; }
        public Nullable<long> student_subject_mark_id { get; set; }
        public Nullable<long> subject_id { get; set; }
        public Nullable<long> subject_exam_id { get; set; }
    
        public virtual tbl_mark_type tbl_mark_type { get; set; }
        public virtual tbl_semester_subject tbl_semester_subject { get; set; }
        public virtual tbl_special_point tbl_special_point { get; set; }
        public virtual tbl_student tbl_student { get; set; }
        public virtual tbl_student_course_subject tbl_student_course_subject { get; set; }
        public virtual tbl_subject_exam tbl_subject_exam { get; set; }
        public virtual tbl_student_semester_subject_exam_room tbl_student_semester_subject_exam_room { get; set; }
        public virtual tbl_subject tbl_subject { get; set; }
        public virtual tbl_student_subject_mark tbl_student_subject_mark { get; set; }
    }
}
