//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_discount_tuition_fee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_discount_tuition_fee()
        {
            this.tbl_discount_tuition_fee_item = new HashSet<tbl_discount_tuition_fee_item>();
            this.tbl_student_tuition_fee_calculate = new HashSet<tbl_student_tuition_fee_calculate>();
        }
    
        public long id { get; set; }
        public System.DateTime create_date { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string uuid_key { get; set; }
        public Nullable<bool> voided { get; set; }
        public string code { get; set; }
        public Nullable<bool> is_discount_all { get; set; }
        public Nullable<bool> is_discount_all_case { get; set; }
        public string name { get; set; }
        public Nullable<double> proportion_discount { get; set; }
        public Nullable<long> course_year_id { get; set; }
        public Nullable<long> semester_id { get; set; }
        public Nullable<long> student_object_id { get; set; }
    
        public virtual tbl_course_year tbl_course_year { get; set; }
        public virtual tbl_student_object tbl_student_object { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_discount_tuition_fee_item> tbl_discount_tuition_fee_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_tuition_fee_calculate> tbl_student_tuition_fee_calculate { get; set; }
        public virtual tbl_semester tbl_semester { get; set; }
    }
}
