//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_behavior_mark_classification_standard
    {
        public long id { get; set; }
        public System.DateTime create_date { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string uuid_key { get; set; }
        public Nullable<bool> voided { get; set; }
        public Nullable<int> classification { get; set; }
        public Nullable<double> highest_mark { get; set; }
        public Nullable<bool> is_end_course_year { get; set; }
        public Nullable<double> lowest_mark { get; set; }
        public Nullable<long> course_year_id { get; set; }
        public Nullable<long> highest_discipline_id { get; set; }
        public Nullable<long> school_year_id { get; set; }
        public Nullable<long> semester_id { get; set; }
    
        public virtual tbl_discipline tbl_discipline { get; set; }
        public virtual tbl_semester tbl_semester { get; set; }
        public virtual tbl_course_year tbl_course_year { get; set; }
        public virtual tbl_shool_year tbl_shool_year { get; set; }
    }
}
