//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_student_candidate_profile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_student_candidate_profile()
        {
            this.tbl_student = new HashSet<tbl_student>();
        }
    
        public long id { get; set; }
        public System.DateTime create_date { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string uuid_key { get; set; }
        public Nullable<bool> voided { get; set; }
        public string admission { get; set; }
        public string admission_combination { get; set; }
        public string admissions_committee { get; set; }
        public Nullable<int> admissions_year { get; set; }
        public string area { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public string candidate_code { get; set; }
        public Nullable<bool> check_admission_fee { get; set; }
        public string contact_address { get; set; }
        public string district_code { get; set; }
        public Nullable<double> dtc0 { get; set; }
        public string exam_room { get; set; }
        public string first_group { get; set; }
        public string first_name { get; set; }
        public string first_school { get; set; }
        public string first_speciality_code { get; set; }
        public string first_speciality_detail_code { get; set; }
        public Nullable<double> first_subject_name { get; set; }
        public Nullable<double> first_subject_score { get; set; }
        public string gender { get; set; }
        public string grade_eleven { get; set; }
        public string grade_ten { get; set; }
        public string grade_twelve { get; set; }
        public string high_school_conduct { get; set; }
        public string high_school_grade { get; set; }
        public string high_school_graduation { get; set; }
        public string high_school_graduation_place { get; set; }
        public Nullable<int> high_school_graduation_year { get; set; }
        public string id_number { get; set; }
        public Nullable<bool> confirm_admission { get; set; }
        public Nullable<bool> recruited_directly { get; set; }
        public string last_name { get; set; }
        public string note { get; set; }
        public string phone_number { get; set; }
        public string priority_group { get; set; }
        public string province_code { get; set; }
        public string reason { get; set; }
        public string second_group { get; set; }
        public string second_school { get; set; }
        public string second_speciality_code { get; set; }
        public Nullable<double> second_subject_name { get; set; }
        public Nullable<double> second_subject_score { get; set; }
        public string stage { get; set; }
        public string student_code { get; set; }
        public string student_object_code { get; set; }
        public Nullable<double> third_subject_name { get; set; }
        public Nullable<double> third_subject_score { get; set; }
        public Nullable<double> total_score { get; set; }
        public Nullable<long> training_base_id { get; set; }
        public string training_units { get; set; }
        public Nullable<long> address_unit_id { get; set; }
        public Nullable<long> course_year_id { get; set; }
        public Nullable<long> education_type_id { get; set; }
        public Nullable<long> enrollment_class_id { get; set; }
        public string current_whereabouts { get; set; }
        public string email { get; set; }
        public string ethnic { get; set; }
        public string father_name { get; set; }
        public string father_phone_number { get; set; }
        public Nullable<System.DateTime> id_number_date_of_issue { get; set; }
        public string id_number_place_of_issue { get; set; }
        public string mother_name { get; set; }
        public string mother_phone_number { get; set; }
        public string native_village { get; set; }
        public string place_of_birth { get; set; }
        public string place_of_permanent_residence_registration { get; set; }
        public string religion { get; set; }
        public Nullable<long> student_id { get; set; }
        public string address_little_brother2 { get; set; }
        public string address_old_brother1 { get; set; }
        public string address_old_brother2 { get; set; }
        public string address_old_brother3 { get; set; }
        public string address_old_sister1 { get; set; }
        public string address_old_sister2 { get; set; }
        public string address_old_sister3 { get; set; }
        public string address_little_brother1 { get; set; }
        public string address_little_brother3 { get; set; }
        public Nullable<System.DateTime> communist_adminssion_date { get; set; }
        public string communist_adminssion_place { get; set; }
        public string country_code { get; set; }
        public Nullable<System.DateTime> father_date_of_birth { get; set; }
        public string father_job { get; set; }
        public Nullable<int> father_year_of_birth { get; set; }
        public Nullable<System.DateTime> group_admission_date { get; set; }
        public string group_admission_place { get; set; }
        public Nullable<bool> is_confirm { get; set; }
        public string link_fb { get; set; }
        public Nullable<System.DateTime> mother_date_of_birth { get; set; }
        public string mother_job { get; set; }
        public Nullable<int> mother_year_of_birth { get; set; }
        public string name_little_brother1 { get; set; }
        public string name_little_brother2 { get; set; }
        public string name_little_brother3 { get; set; }
        public string name_old_brother1 { get; set; }
        public string name_old_brother2 { get; set; }
        public string name_old_brother3 { get; set; }
        public string name_old_sister1 { get; set; }
        public string name_old_sister2 { get; set; }
        public string name_old_sister3 { get; set; }
        public string ward_code { get; set; }
        public string ward_name { get; set; }
        public string wishToEnroll1 { get; set; }
        public string wishToEnroll2 { get; set; }
        public string wishToEnroll3 { get; set; }
        public string wishToEnroll4 { get; set; }
        public Nullable<int> year_little_Brother1 { get; set; }
        public Nullable<int> year_little_Brother2 { get; set; }
        public Nullable<int> year_little_Brother3 { get; set; }
        public Nullable<int> year_old_brother1 { get; set; }
        public Nullable<int> year_old_brother2 { get; set; }
        public Nullable<int> year_old_brother3 { get; set; }
        public Nullable<int> year_old_sister1 { get; set; }
        public Nullable<int> year_old_sister2 { get; set; }
        public Nullable<int> year_old_sister3 { get; set; }
        public Nullable<long> country_id { get; set; }
        public Nullable<long> district_id { get; set; }
        public Nullable<long> ethnics_id { get; set; }
        public Nullable<long> province_id { get; set; }
        public Nullable<long> religion_id { get; set; }
        public Nullable<long> student_object_id { get; set; }
        public Nullable<long> user_id { get; set; }
        public Nullable<long> ward_id { get; set; }
        public string insurance_card_code { get; set; }
        public string district_name { get; set; }
        public string province_name { get; set; }
        public string father_address { get; set; }
        public string mother_address { get; set; }
        public string first_name_subject { get; set; }
        public string second_name_subject { get; set; }
        public string third_name_subject { get; set; }
    
        public virtual tbl_administrative_unit tbl_administrative_unit { get; set; }
        public virtual tbl_administrative_unit tbl_administrative_unit1 { get; set; }
        public virtual tbl_administrative_unit tbl_administrative_unit2 { get; set; }
        public virtual tbl_administrative_unit tbl_administrative_unit3 { get; set; }
        public virtual tbl_country tbl_country { get; set; }
        public virtual tbl_course_year tbl_course_year { get; set; }
        public virtual tbl_education_type tbl_education_type { get; set; }
        public virtual tbl_enrollment_class tbl_enrollment_class { get; set; }
        public virtual tbl_ethnics tbl_ethnics { get; set; }
        public virtual tbl_religion tbl_religion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student> tbl_student { get; set; }
        public virtual tbl_student tbl_student1 { get; set; }
        public virtual tbl_student_object tbl_student_object { get; set; }
        public virtual tbl_user tbl_user { get; set; }
    }
}
