//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_semester_subject_exam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_semester_subject_exam()
        {
            this.tbl_exam_date = new HashSet<tbl_exam_date>();
            this.tbl_semester_subject_exam_room = new HashSet<tbl_semester_subject_exam_room>();
            this.tbl_training_base_semester_subject_exam = new HashSet<tbl_training_base_semester_subject_exam>();
            this.tbl_semester_subject_exam_date = new HashSet<tbl_semester_subject_exam_date>();
            this.tbl_testBag_create_time = new HashSet<tbl_testBag_create_time>();
            this.tbl_test_bag = new HashSet<tbl_test_bag>();
            this.tbl_semester_subject_exam_course_subject = new HashSet<tbl_semester_subject_exam_course_subject>();
            this.tbl_student_semester_subject_exam = new HashSet<tbl_student_semester_subject_exam>();
        }
    
        public long id { get; set; }
        public System.DateTime create_date { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string uuid_key { get; set; }
        public Nullable<bool> voided { get; set; }
        public string description { get; set; }
        public Nullable<int> exam_round { get; set; }
        public Nullable<int> number_estimate_student { get; set; }
        public Nullable<int> number_room { get; set; }
        public Nullable<int> number_student { get; set; }
        public Nullable<long> course_year_id { get; set; }
        public Nullable<long> exam_register_period_id { get; set; }
        public Nullable<long> register_period_id { get; set; }
        public Nullable<long> semester_id { get; set; }
        public Nullable<long> subject_id { get; set; }
        public Nullable<long> semester_exam_period_id { get; set; }
        public Nullable<long> semester_subject_id { get; set; }
        public Nullable<long> exam_type_id { get; set; }
        public string name { get; set; }
    
        public virtual tbl_course_year tbl_course_year { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_exam_date> tbl_exam_date { get; set; }
        public virtual tbl_exam_register_period tbl_exam_register_period { get; set; }
        public virtual tbl_exam_type tbl_exam_type { get; set; }
        public virtual tbl_semester tbl_semester { get; set; }
        public virtual tbl_semester_exam_period tbl_semester_exam_period { get; set; }
        public virtual tbl_semester_register_period tbl_semester_register_period { get; set; }
        public virtual tbl_semester_subject tbl_semester_subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_semester_subject_exam_room> tbl_semester_subject_exam_room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_training_base_semester_subject_exam> tbl_training_base_semester_subject_exam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_semester_subject_exam_date> tbl_semester_subject_exam_date { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_testBag_create_time> tbl_testBag_create_time { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_test_bag> tbl_test_bag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_semester_subject_exam_course_subject> tbl_semester_subject_exam_course_subject { get; set; }
        public virtual tbl_subject tbl_subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_semester_subject_exam> tbl_student_semester_subject_exam { get; set; }
    }
}
