//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_study_alert_condition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_study_alert_condition()
        {
            this.tbl_student_study_alert_level = new HashSet<tbl_student_study_alert_level>();
            this.tbl_study_alert_condition_student_object = new HashSet<tbl_study_alert_condition_student_object>();
            this.tbl_study_alert_condition_certificate = new HashSet<tbl_study_alert_condition_certificate>();
            this.tbl_study_alert_running = new HashSet<tbl_study_alert_running>();
            this.tbl_study_alert_condition_level = new HashSet<tbl_study_alert_condition_level>();
        }
    
        public long id { get; set; }
        public System.DateTime create_date { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string uuid_key { get; set; }
        public Nullable<bool> voided { get; set; }
        public string code { get; set; }
        public Nullable<double> cumumlative_mark { get; set; }
        public Nullable<double> cumulative_mark_2_semester { get; set; }
        public string cumulative_mark_2_semester_operator { get; set; }
        public string cumulative_mark_2_semester_type { get; set; }
        public string cumulativeMarkOperator { get; set; }
        public Nullable<double> cumulative_mark_semester { get; set; }
        public string number_cumulative_mark_semester_operator { get; set; }
        public string cumulative_mark_semester_type { get; set; }
        public string cumumlative_mark_type { get; set; }
        public Nullable<bool> is_include_retain { get; set; }
        public Nullable<bool> is_not_complete_tuition_fee { get; set; }
        public Nullable<bool> is_out_of_duration_time { get; set; }
        public Nullable<double> learning_mark { get; set; }
        public Nullable<double> learning_mark_2_semester { get; set; }
        public string learning_mark_2_semester_operator { get; set; }
        public string learning_mark_2_semester_type { get; set; }
        public string learning_mark_operator { get; set; }
        public Nullable<double> learning_mark_school_year { get; set; }
        public string learning_mark_school_year_operator { get; set; }
        public string learning_mark_school_year_type { get; set; }
        public Nullable<double> learning_mark_semester { get; set; }
        public string learning_semester_operator { get; set; }
        public string learning_semester_type { get; set; }
        public string learning_mark_type { get; set; }
        public Nullable<double> max_duration { get; set; }
        public Nullable<double> max_duration_include_retain { get; set; }
        public string name { get; set; }
        public Nullable<int> number_cumumlative_credit { get; set; }
        public Nullable<int> number_cumulative_credit_2_semester { get; set; }
        public string number_cumulative_credit_2_semester_operator { get; set; }
        public string number_cumumlative_credit_operator { get; set; }
        public Nullable<int> number_cumulative_credit_semester { get; set; }
        public string number_cumulative_credit_semester_operator { get; set; }
        public Nullable<int> number_discipline { get; set; }
        public Nullable<int> number_learning_credit { get; set; }
        public Nullable<int> number_learning_credit_2_semester { get; set; }
        public string number_learning_credit_2_semester_operator { get; set; }
        public string number_learning_credit_operator { get; set; }
        public Nullable<int> number_learning_credit_school_year { get; set; }
        public string number_learning_credit_school_year_operator { get; set; }
        public Nullable<int> number_learning_credit_semester { get; set; }
        public string number_learning_credit_semester_operator { get; set; }
        public Nullable<int> study_alert_type { get; set; }
        public Nullable<long> course_year_id { get; set; }
        public Nullable<long> discipline_id { get; set; }
        public Nullable<long> class_id { get; set; }
        public Nullable<long> semester_id { get; set; }
        public Nullable<long> speciality_id { get; set; }
        public Nullable<long> study_alert_level_id { get; set; }
        public Nullable<int> number_of_credit_debt { get; set; }
        public string number_of_credit_debt_operator { get; set; }
    
        public virtual tbl_course_year tbl_course_year { get; set; }
        public virtual tbl_discipline tbl_discipline { get; set; }
        public virtual tbl_enrollment_class tbl_enrollment_class { get; set; }
        public virtual tbl_semester tbl_semester { get; set; }
        public virtual tbl_speciality tbl_speciality { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_study_alert_level> tbl_student_study_alert_level { get; set; }
        public virtual tbl_study_alert_level tbl_study_alert_level { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_study_alert_condition_student_object> tbl_study_alert_condition_student_object { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_study_alert_condition_certificate> tbl_study_alert_condition_certificate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_study_alert_running> tbl_study_alert_running { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_study_alert_condition_level> tbl_study_alert_condition_level { get; set; }
    }
}
