//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_timesheet_detail
    {
        public long id { get; set; }
        public System.DateTime create_date { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string uuid_key { get; set; }
        public Nullable<bool> voided { get; set; }
        public Nullable<double> hours { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public string working_item_title { get; set; }
        public Nullable<long> timesheet_id { get; set; }
    
        public virtual tbl_timesheet tbl_timesheet { get; set; }
    }
}
