//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_voucher_detail_recieve_pay_able_link
    {
        public long id { get; set; }
        public System.DateTime create_date { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string uuid_key { get; set; }
        public Nullable<bool> voided { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<int> is_receive { get; set; }
        public Nullable<System.DateTime> voucherDate { get; set; }
        public Nullable<long> education_voucher_detail_id { get; set; }
        public Nullable<long> receive_pay_able_id { get; set; }
    
        public virtual tbl_education_voucher_detail tbl_education_voucher_detail { get; set; }
        public virtual tbl_receive_pay_able tbl_receive_pay_able { get; set; }
    }
}
