//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_student_reward_condition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_student_reward_condition()
        {
            this.tbl_student_reward = new HashSet<tbl_student_reward>();
        }
    
        public long id { get; set; }
        public System.DateTime create_date { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string uuid_key { get; set; }
        public Nullable<bool> voided { get; set; }
        public Nullable<int> academic_classification { get; set; }
        public Nullable<int> behavior_classification { get; set; }
        public string char_mark { get; set; }
        public Nullable<int> inspect_course_year { get; set; }
        public Nullable<int> inspect_school_year { get; set; }
        public Nullable<bool> is_disciplined { get; set; }
        public Nullable<bool> is_end_course_year { get; set; }
        public Nullable<bool> is_rewarded { get; set; }
        public Nullable<double> mark10 { get; set; }
        public Nullable<double> mark4 { get; set; }
        public Nullable<int> number_of_retest_allowed { get; set; }
        public Nullable<int> reward_name { get; set; }
        public Nullable<long> course_year_id { get; set; }
        public Nullable<long> school_year_id { get; set; }
    
        public virtual tbl_course_year tbl_course_year { get; set; }
        public virtual tbl_shool_year tbl_shool_year { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_reward> tbl_student_reward { get; set; }
    }
}
