//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_education_program_tuition_fee
    {
        public long id { get; set; }
        public System.DateTime create_date { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string uuid_key { get; set; }
        public Nullable<bool> voided { get; set; }
        public Nullable<double> basic_main_spec_fee { get; set; }
        public Nullable<double> basic_second_spec_fee { get; set; }
        public Nullable<bool> is_current { get; set; }
        public Nullable<double> main_spec_fee { get; set; }
        public Nullable<double> main_spec_fee_improve { get; set; }
        public Nullable<double> main_spec_fee_retake { get; set; }
        public Nullable<double> second_spec_fee { get; set; }
        public Nullable<double> second_spec_fee_improve { get; set; }
        public Nullable<double> second_spec_fee_retake { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<long> course_year_id { get; set; }
        public Nullable<long> education_level_id { get; set; }
        public Nullable<long> education_program_id { get; set; }
        public Nullable<long> education_type_id { get; set; }
        public Nullable<long> class_id { get; set; }
        public Nullable<long> register_period_id { get; set; }
        public Nullable<long> semester_id { get; set; }
        public Nullable<long> sepeciality_id { get; set; }
        public Nullable<long> training_base_id { get; set; }
        public Nullable<int> education_program_type { get; set; }
        public Nullable<long> department_id { get; set; }
        public Nullable<long> speciality_id { get; set; }
    
        public virtual tbl_course_year tbl_course_year { get; set; }
        public virtual tbl_department tbl_department { get; set; }
        public virtual tbl_education_level tbl_education_level { get; set; }
        public virtual tbl_education_program tbl_education_program { get; set; }
        public virtual tbl_semester tbl_semester { get; set; }
        public virtual tbl_enrollment_class tbl_enrollment_class { get; set; }
        public virtual tbl_speciality tbl_speciality { get; set; }
        public virtual tbl_training_base tbl_training_base { get; set; }
        public virtual tbl_semester_register_period tbl_semester_register_period { get; set; }
        public virtual tbl_speciality tbl_speciality1 { get; set; }
        public virtual tbl_education_type tbl_education_type { get; set; }
    }
}
