//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_course_subject_timetable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_course_subject_timetable()
        {
            this.tbl_timetable_detail = new HashSet<tbl_timetable_detail>();
            this.tbl_course_subject1 = new HashSet<tbl_course_subject>();
        }
    
        public long id { get; set; }
        public System.DateTime create_date { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string uuid_key { get; set; }
        public Nullable<bool> voided { get; set; }
        public Nullable<int> fromWeek { get; set; }
        public Nullable<double> number_hours { get; set; }
        public Nullable<int> toWeek { get; set; }
        public Nullable<int> week { get; set; }
        public Nullable<long> assistant_teacher_id { get; set; }
        public Nullable<long> end_hour_id { get; set; }
        public Nullable<long> room_id { get; set; }
        public Nullable<long> start_hour_id { get; set; }
        public Nullable<long> teacher_id { get; set; }
        public Nullable<long> course_subject_id { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
    
        public virtual tbl_course_hour tbl_course_hour { get; set; }
        public virtual tbl_course_hour tbl_course_hour1 { get; set; }
        public virtual tbl_course_subject tbl_course_subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_timetable_detail> tbl_timetable_detail { get; set; }
        public virtual tbl_room tbl_room { get; set; }
        public virtual tbl_staff tbl_staff { get; set; }
        public virtual tbl_staff tbl_staff1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_course_subject> tbl_course_subject1 { get; set; }
    }
}
