//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_student_summary_mark
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_student_summary_mark()
        {
            this.tbl_student_school_year_summary_mark = new HashSet<tbl_student_school_year_summary_mark>();
            this.tbl_student_semester_summary_mark = new HashSet<tbl_student_semester_summary_mark>();
        }
    
        public long id { get; set; }
        public System.DateTime create_date { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string uuid_key { get; set; }
        public Nullable<bool> voided { get; set; }
        public string char_mark { get; set; }
        public Nullable<double> first_learning_mark { get; set; }
        public Nullable<double> first_learning_mark4 { get; set; }
        public Nullable<double> first_learning_mark_n2 { get; set; }
        public Nullable<double> first_mark { get; set; }
        public Nullable<double> first_mark4 { get; set; }
        public Nullable<double> first_mark_n2 { get; set; }
        public Nullable<int> first_total_credit { get; set; }
        public Nullable<int> first_total_learning_credit { get; set; }
        public Nullable<double> learning_mark { get; set; }
        public Nullable<double> learning_mark4 { get; set; }
        public Nullable<double> learning_mark4_n2 { get; set; }
        public Nullable<double> learning_mark_n2 { get; set; }
        public Nullable<int> learning_total_credit { get; set; }
        public Nullable<int> learning_total_credit_n2 { get; set; }
        public Nullable<double> mark { get; set; }
        public Nullable<double> mark4 { get; set; }
        public Nullable<double> mark4_n2 { get; set; }
        public Nullable<double> mark_n2 { get; set; }
        public Nullable<int> total_credit { get; set; }
        public Nullable<int> total_credit_n2 { get; set; }
        public Nullable<long> student_id { get; set; }
        public Nullable<bool> is_lock { get; set; }
        public Nullable<bool> is_true { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual tbl_student tbl_student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_school_year_summary_mark> tbl_student_school_year_summary_mark { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_semester_summary_mark> tbl_student_semester_summary_mark { get; set; }
    }
}
