//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_student_course_subject_cancel_fee
    {
        public long id { get; set; }
        public System.DateTime create_date { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string uuid_key { get; set; }
        public Nullable<bool> voided { get; set; }
        public string note { get; set; }
        public Nullable<double> pay_amount { get; set; }
        public Nullable<double> pay_percent { get; set; }
        public Nullable<double> tuition_fee { get; set; }
        public Nullable<long> course_subject_id { get; set; }
        public Nullable<long> receive_pay_able_id { get; set; }
        public Nullable<long> student_id { get; set; }
        public Nullable<long> receive_pay_able_detail_id { get; set; }
        public Nullable<long> student_register_change_id { get; set; }
        public Nullable<double> tuition_fee_discount_percent { get; set; }
        public Nullable<double> tuition_fee_per_credit { get; set; }
    
        public virtual tbl_course_subject tbl_course_subject { get; set; }
        public virtual tbl_receive_pay_able tbl_receive_pay_able { get; set; }
        public virtual tbl_receive_pay_able_detail tbl_receive_pay_able_detail { get; set; }
        public virtual tbl_student tbl_student { get; set; }
        public virtual tbl_student_register_change tbl_student_register_change { get; set; }
    }
}
