//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_student_tuition_fee_calculate_detail
    {
        public long id { get; set; }
        public System.DateTime create_date { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string uuid_key { get; set; }
        public Nullable<bool> voided { get; set; }
        public Nullable<double> basic_fee_unit { get; set; }
        public Nullable<double> discount_percent { get; set; }
        public Nullable<double> discount_value { get; set; }
        public Nullable<double> fee_unit { get; set; }
        public Nullable<int> formula { get; set; }
        public Nullable<bool> is_main_spec { get; set; }
        public Nullable<int> learning_type { get; set; }
        public string note { get; set; }
        public Nullable<double> object_coefficient { get; set; }
        public Nullable<double> rest_amount { get; set; }
        public Nullable<double> subject_coefficient { get; set; }
        public Nullable<double> tuition_fee { get; set; }
        public Nullable<long> feeItem_id { get; set; }
        public Nullable<long> student_course_subject_id { get; set; }
        public Nullable<long> student_tuition_fee_calculate_id { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual tbl_fee_item tbl_fee_item { get; set; }
        public virtual tbl_student_course_subject tbl_student_course_subject { get; set; }
        public virtual tbl_student_tuition_fee_calculate tbl_student_tuition_fee_calculate { get; set; }
    }
}
