//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_student_call_roll
    {
        public long id { get; set; }
        public System.DateTime create_date { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string uuid_key { get; set; }
        public Nullable<bool> voided { get; set; }
        public string note { get; set; }
        public Nullable<int> number_absences { get; set; }
        public Nullable<int> number_hours { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<long> student_id { get; set; }
        public Nullable<long> timetable_detail_id { get; set; }
    
        public virtual tbl_student tbl_student { get; set; }
        public virtual tbl_timetable_detail tbl_timetable_detail { get; set; }
    }
}
