//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_semester_subject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_semester_subject()
        {
            this.tbl_course_subject = new HashSet<tbl_course_subject>();
            this.tbl_semester_subject_learning_skill = new HashSet<tbl_semester_subject_learning_skill>();
            this.tbl_semester_subject_exam = new HashSet<tbl_semester_subject_exam>();
            this.tbl_training_base_semester_subject = new HashSet<tbl_training_base_semester_subject>();
            this.tbl_subject_exam = new HashSet<tbl_subject_exam>();
            this.tbl_student_mark = new HashSet<tbl_student_mark>();
        }
    
        public long id { get; set; }
        public System.DateTime create_date { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string uuid_key { get; set; }
        public Nullable<bool> voided { get; set; }
        public Nullable<int> child_course_type { get; set; }
        public Nullable<bool> is_fee_by_subject { get; set; }
        public Nullable<int> max_number_student_child_course { get; set; }
        public Nullable<int> max_number_student_parent_course { get; set; }
        public Nullable<int> min_number_student_child_course { get; set; }
        public Nullable<int> min_number_student_parent_course { get; set; }
        public Nullable<int> number_child_by_parent { get; set; }
        public Nullable<int> number_course { get; set; }
        public Nullable<double> numberMainSkillHours { get; set; }
        public Nullable<int> parent_course_type { get; set; }
        public Nullable<double> remuneration_coefficient { get; set; }
        public Nullable<double> remuneration_fee { get; set; }
        public Nullable<double> totalNumberHours { get; set; }
        public Nullable<double> tuition_fee { get; set; }
        public Nullable<double> tuition_fee_coefficient { get; set; }
        public Nullable<bool> useByCourseYear { get; set; }
        public Nullable<long> course_year_id { get; set; }
        public Nullable<long> main_learning_skill_id { get; set; }
        public Nullable<long> register_period_id { get; set; }
        public Nullable<long> semester_id { get; set; }
        public Nullable<long> sub_semester_id { get; set; }
        public Nullable<long> subject_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_course_subject> tbl_course_subject { get; set; }
        public virtual tbl_course_year tbl_course_year { get; set; }
        public virtual tbl_learning_skill tbl_learning_skill { get; set; }
        public virtual tbl_semester tbl_semester { get; set; }
        public virtual tbl_semester tbl_semester1 { get; set; }
        public virtual tbl_semester_register_period tbl_semester_register_period { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_semester_subject_learning_skill> tbl_semester_subject_learning_skill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_semester_subject_exam> tbl_semester_subject_exam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_training_base_semester_subject> tbl_training_base_semester_subject { get; set; }
        public virtual tbl_subject tbl_subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_subject_exam> tbl_subject_exam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_mark> tbl_student_mark { get; set; }
    }
}
