//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_discount_tuition_fee_item
    {
        public long id { get; set; }
        public System.DateTime create_date { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string uuid_key { get; set; }
        public Nullable<bool> voided { get; set; }
        public Nullable<double> proportion_discount { get; set; }
        public Nullable<long> discount_tuition_fee_id { get; set; }
        public Nullable<long> fee_item_id { get; set; }
    
        public virtual tbl_discount_tuition_fee tbl_discount_tuition_fee { get; set; }
        public virtual tbl_fee_item tbl_fee_item { get; set; }
    }
}
