//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_criteria_search_student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_criteria_search_student()
        {
            this.tbl_student_graduate_conditional = new HashSet<tbl_student_graduate_conditional>();
            this.tbl_criteria_search_student_except_subject = new HashSet<tbl_criteria_search_student_except_subject>();
        }
    
        public long id { get; set; }
        public System.DateTime create_date { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string uuid_key { get; set; }
        public Nullable<bool> voided { get; set; }
        public Nullable<double> max_mark { get; set; }
        public Nullable<double> max_mark4 { get; set; }
        public Nullable<int> max_number_credit_not_pass { get; set; }
        public Nullable<int> max_number_subject_not_pass { get; set; }
        public Nullable<double> min_mark { get; set; }
        public Nullable<double> min_mark4 { get; set; }
        public string name { get; set; }
        public Nullable<bool> payFullTuitionFees { get; set; }
        public Nullable<long> course_year_id { get; set; }
        public Nullable<long> discipline_id { get; set; }
        public Nullable<long> education_program_id { get; set; }
    
        public virtual tbl_course_year tbl_course_year { get; set; }
        public virtual tbl_education_program tbl_education_program { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_graduate_conditional> tbl_student_graduate_conditional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_criteria_search_student_except_subject> tbl_criteria_search_student_except_subject { get; set; }
        public virtual tbl_discipline tbl_discipline { get; set; }
    }
}
