//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_knowledge_program
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_knowledge_program()
        {
            this.tbl_program_subject = new HashSet<tbl_program_subject>();
            this.tbl_knowledge_program1 = new HashSet<tbl_knowledge_program>();
        }
    
        public long id { get; set; }
        public System.DateTime create_date { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string uuid_key { get; set; }
        public Nullable<bool> voided { get; set; }
        public Nullable<int> block_type { get; set; }
        public Nullable<int> min_number_credit { get; set; }
        public Nullable<int> number_course_subject { get; set; }
        public Nullable<int> total_credit { get; set; }
        public Nullable<long> knowledge_block_id { get; set; }
        public Nullable<long> parent_id { get; set; }
        public Nullable<long> program_id { get; set; }
        public Nullable<long> sub_speciality_id { get; set; }
    
        public virtual tbl_education_program tbl_education_program { get; set; }
        public virtual tbl_knowledge_block tbl_knowledge_block { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_program_subject> tbl_program_subject { get; set; }
        public virtual tbl_speciality tbl_speciality { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_knowledge_program> tbl_knowledge_program1 { get; set; }
        public virtual tbl_knowledge_program tbl_knowledge_program2 { get; set; }
    }
}
