//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_course_subject_config
    {
        public long id { get; set; }
        public System.DateTime create_date { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string uuid_key { get; set; }
        public Nullable<bool> voided { get; set; }
        public Nullable<int> configType { get; set; }
        public Nullable<bool> is_denied { get; set; }
        public Nullable<bool> is_grant { get; set; }
        public Nullable<long> course_subject_id { get; set; }
        public Nullable<long> course_year_id { get; set; }
        public Nullable<long> deparment_id { get; set; }
        public Nullable<long> enrollment_class_id { get; set; }
        public Nullable<long> program_id { get; set; }
        public Nullable<long> speciality_id { get; set; }
    
        public virtual tbl_course_subject tbl_course_subject { get; set; }
        public virtual tbl_speciality tbl_speciality { get; set; }
        public virtual tbl_department tbl_department { get; set; }
        public virtual tbl_education_program tbl_education_program { get; set; }
        public virtual tbl_course_year tbl_course_year { get; set; }
        public virtual tbl_enrollment_class tbl_enrollment_class { get; set; }
    }
}
