//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_civil_servant_category_grade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_civil_servant_category_grade()
        {
            this.tbl_staff_civil_servant_grade = new HashSet<tbl_staff_civil_servant_grade>();
        }
    
        public long id { get; set; }
        public System.DateTime create_date { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string uuid_key { get; set; }
        public Nullable<bool> voided { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public Nullable<double> salary_coefficient { get; set; }
        public Nullable<long> civil_servant_category_id { get; set; }
        public Nullable<long> civil_servant_grade_id { get; set; }
    
        public virtual tbl_civil_servant_category tbl_civil_servant_category { get; set; }
        public virtual tbl_civil_servant_grade tbl_civil_servant_grade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_staff_civil_servant_grade> tbl_staff_civil_servant_grade { get; set; }
    }
}
