//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_semester_subject_exam_room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_semester_subject_exam_room()
        {
            this.tbl_student_semester_subject_exam_room = new HashSet<tbl_student_semester_subject_exam_room>();
        }
    
        public long id { get; set; }
        public System.DateTime create_date { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string uuid_key { get; set; }
        public Nullable<bool> voided { get; set; }
        public int duration { get; set; }
        public Nullable<System.DateTime> examDate { get; set; }
        public Nullable<bool> is_added_full_to_test_bag { get; set; }
        public Nullable<bool> is_added_to_test_bag { get; set; }
        public Nullable<int> number_expected_student { get; set; }
        public Nullable<int> number_student { get; set; }
        public string roomCode { get; set; }
        public Nullable<long> end_hour_id { get; set; }
        public Nullable<long> exam_hour_id { get; set; }
        public Nullable<long> exam_skill_id { get; set; }
        public Nullable<long> room_id { get; set; }
        public Nullable<long> semester_subject_exam_id { get; set; }
        public Nullable<long> start_hour_id { get; set; }
        public Nullable<long> training_base_id { get; set; }
        public Nullable<long> subject_exam_hour_id { get; set; }
        public Nullable<int> viewOrder { get; set; }
        public Nullable<int> view_order { get; set; }
    
        public virtual tbl_course_hour tbl_course_hour { get; set; }
        public virtual tbl_course_hour tbl_course_hour1 { get; set; }
        public virtual tbl_exam_hour tbl_exam_hour { get; set; }
        public virtual tbl_exam_skill tbl_exam_skill { get; set; }
        public virtual tbl_room tbl_room { get; set; }
        public virtual tbl_semester_subject_exam tbl_semester_subject_exam { get; set; }
        public virtual tbl_semester_subject_exam_hour tbl_semester_subject_exam_hour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_semester_subject_exam_room> tbl_student_semester_subject_exam_room { get; set; }
        public virtual tbl_training_base tbl_training_base { get; set; }
    }
}
