//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_student()
        {
            this.tbl__student_student_group = new HashSet<tbl__student_student_group>();
            this.tbl_education_voucher = new HashSet<tbl_education_voucher>();
            this.tbl_inventory_item = new HashSet<tbl_inventory_item>();
            this.tbl_receive_pay_able = new HashSet<tbl_receive_pay_able>();
            this.tbl_student_school_year_summary_mark = new HashSet<tbl_student_school_year_summary_mark>();
            this.tbl_student_subject_mark = new HashSet<tbl_student_subject_mark>();
            this.tbl_student_expectation_register = new HashSet<tbl_student_expectation_register>();
            this.tbl_student_graduate_conditional = new HashSet<tbl_student_graduate_conditional>();
            this.tbl_student_not_complete_fee_semester = new HashSet<tbl_student_not_complete_fee_semester>();
            this.tbl_student_course_subject_edited = new HashSet<tbl_student_course_subject_edited>();
            this.tbl_student_study_alert_level = new HashSet<tbl_student_study_alert_level>();
            this.tbl_student_course_subject_history = new HashSet<tbl_student_course_subject_history>();
            this.tbl_student_discipline = new HashSet<tbl_student_discipline>();
            this.tbl_student_research = new HashSet<tbl_student_research>();
            this.tbl_student_scholarship_stock = new HashSet<tbl_student_scholarship_stock>();
            this.tbl_student_object_student = new HashSet<tbl_student_object_student>();
            this.tbl_student_semester_summary = new HashSet<tbl_student_semester_summary>();
            this.tbl_student_tuition_fee_calculate = new HashSet<tbl_student_tuition_fee_calculate>();
            this.tbl_student_semester_behavior_mark = new HashSet<tbl_student_semester_behavior_mark>();
            this.tbl_student_decision = new HashSet<tbl_student_decision>();
            this.tbl_student_reward = new HashSet<tbl_student_reward>();
            this.tbl_student_semester_reward_scholarship = new HashSet<tbl_student_semester_reward_scholarship>();
            this.tbl_student_semester_subject_exam_room = new HashSet<tbl_student_semester_subject_exam_room>();
            this.tbl_student_graduate = new HashSet<tbl_student_graduate>();
            this.tbl_student_summary_mark = new HashSet<tbl_student_summary_mark>();
            this.tbl_student_semester_subject_exam = new HashSet<tbl_student_semester_subject_exam>();
            this.tbl_student_mark = new HashSet<tbl_student_mark>();
            this.tbl_student_student_private_document = new HashSet<tbl_student_student_private_document>();
            this.tbl_student_call_roll = new HashSet<tbl_student_call_roll>();
            this.tbl_student_education_program = new HashSet<tbl_student_education_program>();
            this.tbl_student_register_change = new HashSet<tbl_student_register_change>();
            this.tbl_student_candidate_profile1 = new HashSet<tbl_student_candidate_profile>();
            this.tbl_student_course_subject = new HashSet<tbl_student_course_subject>();
            this.tbl_student_semester_summary_mark = new HashSet<tbl_student_semester_summary_mark>();
            this.tbl_student_process_assessment_point = new HashSet<tbl_student_process_assessment_point>();
            this.tbl_student_object_student_semester = new HashSet<tbl_student_object_student_semester>();
            this.tbl_student_certificate = new HashSet<tbl_student_certificate>();
            this.tbl_student_course_subject_cancel_fee = new HashSet<tbl_student_course_subject_cancel_fee>();
        }
    
        public string bank_account { get; set; }
        public string bank_name { get; set; }
        public Nullable<System.DateTime> father_birth_date { get; set; }
        public string father_full_name { get; set; }
        public Nullable<int> high_school_graduation_year { get; set; }
        public Nullable<bool> is_boarder { get; set; }
        public Nullable<System.DateTime> mother_birth_date { get; set; }
        public string mother_full_name { get; set; }
        public Nullable<int> status { get; set; }
        public string student_code { get; set; }
        public Nullable<int> year_of_admission { get; set; }
        public long id { get; set; }
        public Nullable<long> candidate_profile_id { get; set; }
        public Nullable<long> class_id { get; set; }
        public Nullable<long> father_profession_id { get; set; }
        public Nullable<long> mother_profession_id { get; set; }
        public string father_phone_number { get; set; }
        public string mother_phone_number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl__student_student_group> tbl__student_student_group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_education_voucher> tbl_education_voucher { get; set; }
        public virtual tbl_enrollment_class tbl_enrollment_class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_inventory_item> tbl_inventory_item { get; set; }
        public virtual tbl_profession tbl_profession { get; set; }
        public virtual tbl_profession tbl_profession1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_receive_pay_able> tbl_receive_pay_able { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_school_year_summary_mark> tbl_student_school_year_summary_mark { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_subject_mark> tbl_student_subject_mark { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_expectation_register> tbl_student_expectation_register { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_graduate_conditional> tbl_student_graduate_conditional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_not_complete_fee_semester> tbl_student_not_complete_fee_semester { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_course_subject_edited> tbl_student_course_subject_edited { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_study_alert_level> tbl_student_study_alert_level { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_course_subject_history> tbl_student_course_subject_history { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_discipline> tbl_student_discipline { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_research> tbl_student_research { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_scholarship_stock> tbl_student_scholarship_stock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_object_student> tbl_student_object_student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_semester_summary> tbl_student_semester_summary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_tuition_fee_calculate> tbl_student_tuition_fee_calculate { get; set; }
        public virtual tbl_student_candidate_profile tbl_student_candidate_profile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_semester_behavior_mark> tbl_student_semester_behavior_mark { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_decision> tbl_student_decision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_reward> tbl_student_reward { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_semester_reward_scholarship> tbl_student_semester_reward_scholarship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_semester_subject_exam_room> tbl_student_semester_subject_exam_room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_graduate> tbl_student_graduate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_summary_mark> tbl_student_summary_mark { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_semester_subject_exam> tbl_student_semester_subject_exam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_mark> tbl_student_mark { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_student_private_document> tbl_student_student_private_document { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_call_roll> tbl_student_call_roll { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_education_program> tbl_student_education_program { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_register_change> tbl_student_register_change { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_candidate_profile> tbl_student_candidate_profile1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_course_subject> tbl_student_course_subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_semester_summary_mark> tbl_student_semester_summary_mark { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_process_assessment_point> tbl_student_process_assessment_point { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_object_student_semester> tbl_student_object_student_semester { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_certificate> tbl_student_certificate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_course_subject_cancel_fee> tbl_student_course_subject_cancel_fee { get; set; }
    }
}
