//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_student_course_subject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_student_course_subject()
        {
            this.tbl_student_tuition_fee_calculate_detail = new HashSet<tbl_student_tuition_fee_calculate_detail>();
            this.tbl_student_mark = new HashSet<tbl_student_mark>();
            this.tbl_student_semester_subject_exam_room = new HashSet<tbl_student_semester_subject_exam_room>();
            this.tbl_student_semester_subject_exam = new HashSet<tbl_student_semester_subject_exam>();
        }
    
        public long id { get; set; }
        public System.DateTime create_date { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string uuid_key { get; set; }
        public Nullable<bool> voided { get; set; }
        public Nullable<int> exam_status { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> study_time { get; set; }
        public Nullable<int> subject_status { get; set; }
        public Nullable<double> tuition_fee { get; set; }
        public Nullable<long> course_subject_id { get; set; }
        public Nullable<long> student_id { get; set; }
        public Nullable<int> reg_type { get; set; }
    
        public virtual tbl_course_subject tbl_course_subject { get; set; }
        public virtual tbl_student tbl_student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_tuition_fee_calculate_detail> tbl_student_tuition_fee_calculate_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_mark> tbl_student_mark { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_semester_subject_exam_room> tbl_student_semester_subject_exam_room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_semester_subject_exam> tbl_student_semester_subject_exam { get; set; }
    }
}
