//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_budget_distribution
    {
        public Nullable<double> actually_fund { get; set; }
        public Nullable<double> multilevel { get; set; }
        public Nullable<int> number_student { get; set; }
        public Nullable<double> residual { get; set; }
        public Nullable<double> total_funds { get; set; }
        public long id { get; set; }
        public Nullable<long> course_year_id { get; set; }
        public Nullable<long> department_id { get; set; }
        public Nullable<long> class_id { get; set; }
        public Nullable<long> semester_id { get; set; }
        public Nullable<long> speciality_id { get; set; }
    
        public virtual tbl_semester tbl_semester { get; set; }
        public virtual tbl_speciality tbl_speciality { get; set; }
        public virtual tbl_person tbl_person { get; set; }
        public virtual tbl_course_year tbl_course_year { get; set; }
        public virtual tbl_department tbl_department { get; set; }
        public virtual tbl_enrollment_class tbl_enrollment_class { get; set; }
    }
}
