//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_calendar_event_attendee
    {
        public long id { get; set; }
        public Nullable<int> attendee_type { get; set; }
        public System.DateTime create_date { get; set; }
        public string created_by { get; set; }
        public string display_name { get; set; }
        public string email { get; set; }
        public Nullable<bool> is_chair_person { get; set; }
        public Nullable<bool> optional { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public Nullable<int> visibility { get; set; }
        public Nullable<long> department_id { get; set; }
        public long event_id { get; set; }
        public Nullable<long> staff_id { get; set; }
    
        public virtual tbl_calendar_event tbl_calendar_event { get; set; }
        public virtual tbl_staff tbl_staff { get; set; }
        public virtual tbl_department tbl_department { get; set; }
    }
}
