//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_person()
        {
            this.tbl_calendar_event = new HashSet<tbl_calendar_event>();
            this.tbl_calendar_event1 = new HashSet<tbl_calendar_event>();
            this.tbl_person_address = new HashSet<tbl_person_address>();
        }
    
        public long id { get; set; }
        public System.DateTime create_date { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string uuid_key { get; set; }
        public Nullable<bool> voided { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public string birth_place { get; set; }
        public string carrer { get; set; }
        public Nullable<System.DateTime> communist_party_join_date { get; set; }
        public Nullable<System.DateTime> communist_youth_union_join_date { get; set; }
        public string display_name { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string first_name { get; set; }
        public string gender { get; set; }
        public string id_number { get; set; }
        public string id_number_issue_by { get; set; }
        public Nullable<System.DateTime> id_number_issue_date { get; set; }
        public string image_path { get; set; }
        public Nullable<bool> is_dead { get; set; }
        public string last_name { get; set; }
        public Nullable<int> marital_status { get; set; }
        public string phone_number { get; set; }
        public Nullable<bool> photo_cropped { get; set; }
        public string short_name { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<long> ethnics_id { get; set; }
        public Nullable<long> family_social_class_id { get; set; }
        public Nullable<long> family_social_priority_id { get; set; }
        public Nullable<long> country_id { get; set; }
        public Nullable<long> native_village { get; set; }
        public Nullable<long> personal_social_priority_id { get; set; }
        public Nullable<long> religion_id { get; set; }
        public Nullable<long> user_id { get; set; }
    
        public virtual tbl_administrative_unit tbl_administrative_unit { get; set; }
        public virtual tbl_budget_distribution tbl_budget_distribution { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_calendar_event> tbl_calendar_event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_calendar_event> tbl_calendar_event1 { get; set; }
        public virtual tbl_country tbl_country { get; set; }
        public virtual tbl_ethnics tbl_ethnics { get; set; }
        public virtual tbl_social_priority tbl_social_priority { get; set; }
        public virtual tbl_social_priority tbl_social_priority1 { get; set; }
        public virtual tbl_user tbl_user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_person_address> tbl_person_address { get; set; }
        public virtual tbl_religion tbl_religion { get; set; }
        public virtual tbl_social_class tbl_social_class { get; set; }
    }
}
