//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_calendar_event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_calendar_event()
        {
            this.tbl_calendar_event_attachment = new HashSet<tbl_calendar_event_attachment>();
            this.tbl_calendar_event_car = new HashSet<tbl_calendar_event_car>();
            this.tbl_calendar_event_attendee = new HashSet<tbl_calendar_event_attendee>();
        }
    
        public long id { get; set; }
        public System.DateTime create_date { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string uuid_key { get; set; }
        public Nullable<bool> voided { get; set; }
        public bool car_registered { get; set; }
        public string chair_person_name { get; set; }
        public string content_by { get; set; }
        public string description { get; set; }
        public Nullable<int> duplicate { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public int event_type { get; set; }
        public bool is_other_chair_person { get; set; }
        public string last_name { get; set; }
        public string last_update_person_name { get; set; }
        public string location { get; set; }
        public Nullable<System.DateTime> origin_end_time { get; set; }
        public Nullable<System.DateTime> origin_start_time { get; set; }
        public string other_attendees { get; set; }
        public bool other_location { get; set; }
        public Nullable<int> persons_require_travelling { get; set; }
        public int scope { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public int event_status { get; set; }
        public string title { get; set; }
        public Nullable<long> person_creator_id { get; set; }
        public Nullable<long> dep_creator_id { get; set; }
        public Nullable<long> owner_department_id { get; set; }
        public Nullable<long> owner_person_id { get; set; }
        public Nullable<long> priority_id { get; set; }
        public Nullable<long> room_id { get; set; }
    
        public virtual tbl_calendar_event_priority tbl_calendar_event_priority { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_calendar_event_attachment> tbl_calendar_event_attachment { get; set; }
        public virtual tbl_person tbl_person { get; set; }
        public virtual tbl_person tbl_person1 { get; set; }
        public virtual tbl_department tbl_department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_calendar_event_car> tbl_calendar_event_car { get; set; }
        public virtual tbl_department tbl_department1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_calendar_event_attendee> tbl_calendar_event_attendee { get; set; }
        public virtual tbl_room tbl_room { get; set; }
    }
}
