//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_enrollment_class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_enrollment_class()
        {
            this.tbl_budget_distribution = new HashSet<tbl_budget_distribution>();
            this.tbl_course_subject = new HashSet<tbl_course_subject>();
            this.tbl_course_subject_config = new HashSet<tbl_course_subject_config>();
            this.tbl_education_program_tuition_fee = new HashSet<tbl_education_program_tuition_fee>();
            this.tbl_student_candidate_profile = new HashSet<tbl_student_candidate_profile>();
            this.tbl_register_period_time_config = new HashSet<tbl_register_period_time_config>();
            this.tbl_student = new HashSet<tbl_student>();
            this.tbl_study_alert_condition = new HashSet<tbl_study_alert_condition>();
            this.tbl_scholarship_condition = new HashSet<tbl_scholarship_condition>();
        }
    
        public long id { get; set; }
        public System.DateTime create_date { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string uuid_key { get; set; }
        public Nullable<bool> voided { get; set; }
        public string classCode { get; set; }
        public string className { get; set; }
        public Nullable<long> number_of_student { get; set; }
        public Nullable<int> schoolYear { get; set; }
        public Nullable<long> course_year_id { get; set; }
        public Nullable<long> department_id { get; set; }
        public Nullable<long> education_id { get; set; }
        public Nullable<long> speciality_id { get; set; }
        public Nullable<long> staff_id { get; set; }
        public Nullable<long> training_base_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_budget_distribution> tbl_budget_distribution { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_course_subject> tbl_course_subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_course_subject_config> tbl_course_subject_config { get; set; }
        public virtual tbl_course_year tbl_course_year { get; set; }
        public virtual tbl_department tbl_department { get; set; }
        public virtual tbl_education_level tbl_education_level { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_education_program_tuition_fee> tbl_education_program_tuition_fee { get; set; }
        public virtual tbl_training_base tbl_training_base { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student_candidate_profile> tbl_student_candidate_profile { get; set; }
        public virtual tbl_staff tbl_staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_register_period_time_config> tbl_register_period_time_config { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_student> tbl_student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_study_alert_condition> tbl_study_alert_condition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_scholarship_condition> tbl_scholarship_condition { get; set; }
        public virtual tbl_speciality tbl_speciality { get; set; }
    }
}
