//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_timesheet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_timesheet()
        {
            this.tbl_timesheet_detail = new HashSet<tbl_timesheet_detail>();
        }
    
        public long id { get; set; }
        public System.DateTime create_date { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string uuid_key { get; set; }
        public Nullable<bool> voided { get; set; }
        public Nullable<int> approve_status { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<double> total_hours { get; set; }
        public Nullable<System.DateTime> working_date { get; set; }
        public Nullable<long> employee_id { get; set; }
        public Nullable<long> shift_work_id { get; set; }
        public Nullable<long> working_status_id { get; set; }
    
        public virtual tbl_shift_work tbl_shift_work { get; set; }
        public virtual tbl_staff tbl_staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_timesheet_detail> tbl_timesheet_detail { get; set; }
        public virtual tbl_working_status tbl_working_status { get; set; }
    }
}
