//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TLU_SAMSEntities : DbContext
    {
        public TLU_SAMSEntities()
            : base("name=TLU_SAMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CollectionStatu> CollectionStatus { get; set; }
        public virtual DbSet<oauth_access_token> oauth_access_token { get; set; }
        public virtual DbSet<oauth_client_details> oauth_client_details { get; set; }
        public virtual DbSet<student_admission_infomation> student_admission_infomation { get; set; }
        public virtual DbSet<StudentDocument> StudentDocuments { get; set; }
        public virtual DbSet<tbl__student_student_group> tbl__student_student_group { get; set; }
        public virtual DbSet<tbl_academic_title> tbl_academic_title { get; set; }
        public virtual DbSet<tbl_activity_log> tbl_activity_log { get; set; }
        public virtual DbSet<tbl_administrative_unit> tbl_administrative_unit { get; set; }
        public virtual DbSet<tbl_behavior_mark_classification_standard> tbl_behavior_mark_classification_standard { get; set; }
        public virtual DbSet<tbl_behavior_mark_criteria> tbl_behavior_mark_criteria { get; set; }
        public virtual DbSet<tbl_budget_distribution> tbl_budget_distribution { get; set; }
        public virtual DbSet<tbl_building> tbl_building { get; set; }
        public virtual DbSet<tbl_calendar_event> tbl_calendar_event { get; set; }
        public virtual DbSet<tbl_calendar_event_attachment> tbl_calendar_event_attachment { get; set; }
        public virtual DbSet<tbl_calendar_event_attendee> tbl_calendar_event_attendee { get; set; }
        public virtual DbSet<tbl_calendar_event_car> tbl_calendar_event_car { get; set; }
        public virtual DbSet<tbl_calendar_event_priority> tbl_calendar_event_priority { get; set; }
        public virtual DbSet<tbl_certificate> tbl_certificate { get; set; }
        public virtual DbSet<tbl_civil_servant_category> tbl_civil_servant_category { get; set; }
        public virtual DbSet<tbl_civil_servant_category_grade> tbl_civil_servant_category_grade { get; set; }
        public virtual DbSet<tbl_civil_servant_grade> tbl_civil_servant_grade { get; set; }
        public virtual DbSet<tbl_classification> tbl_classification { get; set; }
        public virtual DbSet<tbl_country> tbl_country { get; set; }
        public virtual DbSet<tbl_course_hour> tbl_course_hour { get; set; }
        public virtual DbSet<tbl_course_subject> tbl_course_subject { get; set; }
        public virtual DbSet<tbl_course_subject_config> tbl_course_subject_config { get; set; }
        public virtual DbSet<tbl_course_subject_timetable> tbl_course_subject_timetable { get; set; }
        public virtual DbSet<tbl_course_year> tbl_course_year { get; set; }
        public virtual DbSet<tbl_criteria_search_student> tbl_criteria_search_student { get; set; }
        public virtual DbSet<tbl_criteria_search_student_except_subject> tbl_criteria_search_student_except_subject { get; set; }
        public virtual DbSet<tbl_decision> tbl_decision { get; set; }
        public virtual DbSet<tbl_degree_student> tbl_degree_student { get; set; }
        public virtual DbSet<tbl_department> tbl_department { get; set; }
        public virtual DbSet<tbl_discipline> tbl_discipline { get; set; }
        public virtual DbSet<tbl_discount_tuition_fee> tbl_discount_tuition_fee { get; set; }
        public virtual DbSet<tbl_discount_tuition_fee_item> tbl_discount_tuition_fee_item { get; set; }
        public virtual DbSet<tbl_education_degree> tbl_education_degree { get; set; }
        public virtual DbSet<tbl_education_level> tbl_education_level { get; set; }
        public virtual DbSet<tbl_education_program> tbl_education_program { get; set; }
        public virtual DbSet<tbl_education_program_tuition_fee> tbl_education_program_tuition_fee { get; set; }
        public virtual DbSet<tbl_education_type> tbl_education_type { get; set; }
        public virtual DbSet<tbl_education_voucher> tbl_education_voucher { get; set; }
        public virtual DbSet<tbl_education_voucher_detail> tbl_education_voucher_detail { get; set; }
        public virtual DbSet<tbl_enrollment_class> tbl_enrollment_class { get; set; }
        public virtual DbSet<tbl_equivalent_subject> tbl_equivalent_subject { get; set; }
        public virtual DbSet<tbl_ethnics> tbl_ethnics { get; set; }
        public virtual DbSet<tbl_exam> tbl_exam { get; set; }
        public virtual DbSet<tbl_exam_date> tbl_exam_date { get; set; }
        public virtual DbSet<tbl_exam_hour> tbl_exam_hour { get; set; }
        public virtual DbSet<tbl_exam_register_period> tbl_exam_register_period { get; set; }
        public virtual DbSet<tbl_exam_room_period> tbl_exam_room_period { get; set; }
        public virtual DbSet<tbl_exam_skill> tbl_exam_skill { get; set; }
        public virtual DbSet<tbl_exam_status> tbl_exam_status { get; set; }
        public virtual DbSet<tbl_exam_type> tbl_exam_type { get; set; }
        public virtual DbSet<tbl_expectation_register> tbl_expectation_register { get; set; }
        public virtual DbSet<tbl_fee_config_item> tbl_fee_config_item { get; set; }
        public virtual DbSet<tbl_fee_item> tbl_fee_item { get; set; }
        public virtual DbSet<tbl_fee_item_detail> tbl_fee_item_detail { get; set; }
        public virtual DbSet<tbl_file_description> tbl_file_description { get; set; }
        public virtual DbSet<tbl_global_property> tbl_global_property { get; set; }
        public virtual DbSet<tbl_graduation_period> tbl_graduation_period { get; set; }
        public virtual DbSet<tbl_group_subject_program> tbl_group_subject_program { get; set; }
        public virtual DbSet<tbl_inventory_item> tbl_inventory_item { get; set; }
        public virtual DbSet<tbl_knowledge_block> tbl_knowledge_block { get; set; }
        public virtual DbSet<tbl_knowledge_program> tbl_knowledge_program { get; set; }
        public virtual DbSet<tbl_labour_agreement_type> tbl_labour_agreement_type { get; set; }
        public virtual DbSet<tbl_learning_skill> tbl_learning_skill { get; set; }
        public virtual DbSet<tbl_location> tbl_location { get; set; }
        public virtual DbSet<tbl_mark_type> tbl_mark_type { get; set; }
        public virtual DbSet<tbl_organization> tbl_organization { get; set; }
        public virtual DbSet<tbl_organization_user> tbl_organization_user { get; set; }
        public virtual DbSet<tbl_overtime_type> tbl_overtime_type { get; set; }
        public virtual DbSet<tbl_payroll_period> tbl_payroll_period { get; set; }
        public virtual DbSet<tbl_person> tbl_person { get; set; }
        public virtual DbSet<tbl_person_address> tbl_person_address { get; set; }
        public virtual DbSet<tbl_position> tbl_position { get; set; }
        public virtual DbSet<tbl_position_staff> tbl_position_staff { get; set; }
        public virtual DbSet<tbl_position_title> tbl_position_title { get; set; }
        public virtual DbSet<tbl_prerequisite_subject> tbl_prerequisite_subject { get; set; }
        public virtual DbSet<tbl_profession> tbl_profession { get; set; }
        public virtual DbSet<tbl_program_subject> tbl_program_subject { get; set; }
        public virtual DbSet<tbl_receive_pay_able> tbl_receive_pay_able { get; set; }
        public virtual DbSet<tbl_receive_pay_able_detail> tbl_receive_pay_able_detail { get; set; }
        public virtual DbSet<tbl_reg_student_course_subject> tbl_reg_student_course_subject { get; set; }
        public virtual DbSet<tbl_reg_student_subject> tbl_reg_student_subject { get; set; }
        public virtual DbSet<tbl_register_period_time_config> tbl_register_period_time_config { get; set; }
        public virtual DbSet<tbl_religion> tbl_religion { get; set; }
        public virtual DbSet<tbl_reward> tbl_reward { get; set; }
        public virtual DbSet<tbl_reward_decree> tbl_reward_decree { get; set; }
        public virtual DbSet<tbl_role> tbl_role { get; set; }
        public virtual DbSet<tbl_room> tbl_room { get; set; }
        public virtual DbSet<tbl_salary_config> tbl_salary_config { get; set; }
        public virtual DbSet<tbl_salary_config_item> tbl_salary_config_item { get; set; }
        public virtual DbSet<tbl_salary_increment_type> tbl_salary_increment_type { get; set; }
        public virtual DbSet<tbl_salary_item> tbl_salary_item { get; set; }
        public virtual DbSet<tbl_scholarship_condition> tbl_scholarship_condition { get; set; }
        public virtual DbSet<tbl_scholarship_fund> tbl_scholarship_fund { get; set; }
        public virtual DbSet<tbl_scholarship_fund_type> tbl_scholarship_fund_type { get; set; }
        public virtual DbSet<tbl_school_fee_config> tbl_school_fee_config { get; set; }
        public virtual DbSet<tbl_semester> tbl_semester { get; set; }
        public virtual DbSet<tbl_semester_exam_period> tbl_semester_exam_period { get; set; }
        public virtual DbSet<tbl_semester_register_period> tbl_semester_register_period { get; set; }
        public virtual DbSet<tbl_semester_subject> tbl_semester_subject { get; set; }
        public virtual DbSet<tbl_semester_subject_exam> tbl_semester_subject_exam { get; set; }
        public virtual DbSet<tbl_semester_subject_exam_course_subject> tbl_semester_subject_exam_course_subject { get; set; }
        public virtual DbSet<tbl_semester_subject_exam_date> tbl_semester_subject_exam_date { get; set; }
        public virtual DbSet<tbl_semester_subject_exam_hour> tbl_semester_subject_exam_hour { get; set; }
        public virtual DbSet<tbl_semester_subject_exam_hour_room> tbl_semester_subject_exam_hour_room { get; set; }
        public virtual DbSet<tbl_semester_subject_exam_room> tbl_semester_subject_exam_room { get; set; }
        public virtual DbSet<tbl_semester_subject_learning_skill> tbl_semester_subject_learning_skill { get; set; }
        public virtual DbSet<tbl_shift_work> tbl_shift_work { get; set; }
        public virtual DbSet<tbl_shift_work_time_period> tbl_shift_work_time_period { get; set; }
        public virtual DbSet<tbl_shool_year> tbl_shool_year { get; set; }
        public virtual DbSet<tbl_social_class> tbl_social_class { get; set; }
        public virtual DbSet<tbl_social_priority> tbl_social_priority { get; set; }
        public virtual DbSet<tbl_special_point> tbl_special_point { get; set; }
        public virtual DbSet<tbl_speciality> tbl_speciality { get; set; }
        public virtual DbSet<tbl_speciality_program> tbl_speciality_program { get; set; }
        public virtual DbSet<tbl_specialty_admissions_map> tbl_specialty_admissions_map { get; set; }
        public virtual DbSet<tbl_staff> tbl_staff { get; set; }
        public virtual DbSet<tbl_staff_allowance_history> tbl_staff_allowance_history { get; set; }
        public virtual DbSet<tbl_staff_civil_servant_grade> tbl_staff_civil_servant_grade { get; set; }
        public virtual DbSet<tbl_staff_disciplinary_history> tbl_staff_disciplinary_history { get; set; }
        public virtual DbSet<tbl_staff_education_history> tbl_staff_education_history { get; set; }
        public virtual DbSet<tbl_staff_family_relationship> tbl_staff_family_relationship { get; set; }
        public virtual DbSet<tbl_staff_labour_agreement> tbl_staff_labour_agreement { get; set; }
        public virtual DbSet<tbl_staff_labour_agreement_attachment> tbl_staff_labour_agreement_attachment { get; set; }
        public virtual DbSet<tbl_staff_reward_history> tbl_staff_reward_history { get; set; }
        public virtual DbSet<tbl_staff_salary_history> tbl_staff_salary_history { get; set; }
        public virtual DbSet<tbl_staff_salary_property> tbl_staff_salary_property { get; set; }
        public virtual DbSet<tbl_staff_travelling_history> tbl_staff_travelling_history { get; set; }
        public virtual DbSet<tbl_staff_work_schedule> tbl_staff_work_schedule { get; set; }
        public virtual DbSet<tbl_status> tbl_status { get; set; }
        public virtual DbSet<tbl_student> tbl_student { get; set; }
        public virtual DbSet<tbl_student_behavior_criteria_mark> tbl_student_behavior_criteria_mark { get; set; }
        public virtual DbSet<tbl_student_call_roll> tbl_student_call_roll { get; set; }
        public virtual DbSet<tbl_student_candidate_profile> tbl_student_candidate_profile { get; set; }
        public virtual DbSet<tbl_student_certificate> tbl_student_certificate { get; set; }
        public virtual DbSet<tbl_student_code_key> tbl_student_code_key { get; set; }
        public virtual DbSet<tbl_student_course_subject> tbl_student_course_subject { get; set; }
        public virtual DbSet<tbl_student_course_subject_cancel_fee> tbl_student_course_subject_cancel_fee { get; set; }
        public virtual DbSet<tbl_student_course_subject_edited> tbl_student_course_subject_edited { get; set; }
        public virtual DbSet<tbl_student_course_subject_history> tbl_student_course_subject_history { get; set; }
        public virtual DbSet<tbl_student_decision> tbl_student_decision { get; set; }
        public virtual DbSet<tbl_student_decision_type> tbl_student_decision_type { get; set; }
        public virtual DbSet<tbl_student_discipline> tbl_student_discipline { get; set; }
        public virtual DbSet<tbl_student_education_program> tbl_student_education_program { get; set; }
        public virtual DbSet<tbl_student_exam_group> tbl_student_exam_group { get; set; }
        public virtual DbSet<tbl_student_expectation_register> tbl_student_expectation_register { get; set; }
        public virtual DbSet<tbl_student_graduate> tbl_student_graduate { get; set; }
        public virtual DbSet<tbl_student_graduate_conditional> tbl_student_graduate_conditional { get; set; }
        public virtual DbSet<tbl_student_group> tbl_student_group { get; set; }
        public virtual DbSet<tbl_student_mark> tbl_student_mark { get; set; }
        public virtual DbSet<tbl_student_not_complete_fee_semester> tbl_student_not_complete_fee_semester { get; set; }
        public virtual DbSet<tbl_student_object> tbl_student_object { get; set; }
        public virtual DbSet<tbl_student_object_policy> tbl_student_object_policy { get; set; }
        public virtual DbSet<tbl_student_object_student> tbl_student_object_student { get; set; }
        public virtual DbSet<tbl_student_object_student_semester> tbl_student_object_student_semester { get; set; }
        public virtual DbSet<tbl_student_other_fee> tbl_student_other_fee { get; set; }
        public virtual DbSet<tbl_student_private_document> tbl_student_private_document { get; set; }
        public virtual DbSet<tbl_student_process_assessment_point> tbl_student_process_assessment_point { get; set; }
        public virtual DbSet<tbl_student_register_change> tbl_student_register_change { get; set; }
        public virtual DbSet<tbl_student_research> tbl_student_research { get; set; }
        public virtual DbSet<tbl_student_reward> tbl_student_reward { get; set; }
        public virtual DbSet<tbl_student_reward_condition> tbl_student_reward_condition { get; set; }
        public virtual DbSet<tbl_student_scholarship_history> tbl_student_scholarship_history { get; set; }
        public virtual DbSet<tbl_student_scholarship_stock> tbl_student_scholarship_stock { get; set; }
        public virtual DbSet<tbl_student_scholarship_stock_detail> tbl_student_scholarship_stock_detail { get; set; }
        public virtual DbSet<tbl_student_school_year_summary_mark> tbl_student_school_year_summary_mark { get; set; }
        public virtual DbSet<tbl_student_semester_behavior_mark> tbl_student_semester_behavior_mark { get; set; }
        public virtual DbSet<tbl_student_semester_reward_scholarship> tbl_student_semester_reward_scholarship { get; set; }
        public virtual DbSet<tbl_student_semester_subject_exam> tbl_student_semester_subject_exam { get; set; }
        public virtual DbSet<tbl_student_semester_subject_exam_room> tbl_student_semester_subject_exam_room { get; set; }
        public virtual DbSet<tbl_student_semester_summary> tbl_student_semester_summary { get; set; }
        public virtual DbSet<tbl_student_semester_summary_mark> tbl_student_semester_summary_mark { get; set; }
        public virtual DbSet<tbl_student_student_private_document> tbl_student_student_private_document { get; set; }
        public virtual DbSet<tbl_student_study_alert_level> tbl_student_study_alert_level { get; set; }
        public virtual DbSet<tbl_student_subject_mark> tbl_student_subject_mark { get; set; }
        public virtual DbSet<tbl_student_summary_mark> tbl_student_summary_mark { get; set; }
        public virtual DbSet<tbl_student_tuition_fee_calculate> tbl_student_tuition_fee_calculate { get; set; }
        public virtual DbSet<tbl_student_tuition_fee_calculate_detail> tbl_student_tuition_fee_calculate_detail { get; set; }
        public virtual DbSet<tbl_study_alert_condition> tbl_study_alert_condition { get; set; }
        public virtual DbSet<tbl_study_alert_condition_certificate> tbl_study_alert_condition_certificate { get; set; }
        public virtual DbSet<tbl_study_alert_condition_level> tbl_study_alert_condition_level { get; set; }
        public virtual DbSet<tbl_study_alert_condition_student_object> tbl_study_alert_condition_student_object { get; set; }
        public virtual DbSet<tbl_study_alert_level> tbl_study_alert_level { get; set; }
        public virtual DbSet<tbl_study_alert_running> tbl_study_alert_running { get; set; }
        public virtual DbSet<tbl_subject> tbl_subject { get; set; }
        public virtual DbSet<tbl_subject_education_level_type> tbl_subject_education_level_type { get; set; }
        public virtual DbSet<tbl_subject_exam> tbl_subject_exam { get; set; }
        public virtual DbSet<tbl_subject_learning_skill> tbl_subject_learning_skill { get; set; }
        public virtual DbSet<tbl_test_bag> tbl_test_bag { get; set; }
        public virtual DbSet<tbl_testBag_create_time> tbl_testBag_create_time { get; set; }
        public virtual DbSet<tbl_timesheet> tbl_timesheet { get; set; }
        public virtual DbSet<tbl_timesheet_detail> tbl_timesheet_detail { get; set; }
        public virtual DbSet<tbl_timetable_detail> tbl_timetable_detail { get; set; }
        public virtual DbSet<tbl_training_base> tbl_training_base { get; set; }
        public virtual DbSet<tbl_training_base_semester_subject> tbl_training_base_semester_subject { get; set; }
        public virtual DbSet<tbl_training_base_semester_subject_exam> tbl_training_base_semester_subject_exam { get; set; }
        public virtual DbSet<tbl_user> tbl_user { get; set; }
        public virtual DbSet<tbl_user_group> tbl_user_group { get; set; }
        public virtual DbSet<tbl_user_trainning_base> tbl_user_trainning_base { get; set; }
        public virtual DbSet<tbl_voucher_detail_recieve_pay_able_link> tbl_voucher_detail_recieve_pay_able_link { get; set; }
        public virtual DbSet<tbl_voucher_recieve_pay_able> tbl_voucher_recieve_pay_able { get; set; }
        public virtual DbSet<tbl_working_status> tbl_working_status { get; set; }
        public virtual DbSet<CollectionStatus1> CollectionStatus1 { get; set; }
        public virtual DbSet<tbl_1config> tbl_1config { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
